namespace AtlusGfdLib
{
    public enum AnimationKeyframeType
    {
        Type00,
        PRSingle,
        PRSSingle,
        Type03,
        Type04,
        Type05,
        Type06,
        Type07,
        Type08,
        Type09,
        Type10,
        Type11,
        Type12,
        Type13,
        Type14,
        Type15,
        Type16,
        Type17,
        Type18,
        Type19,
        Type20,
        Type21,
        Type22,
        Type23,
        Type24,
        Type25,
        Type26,
        PRSHalf,
        PRHalf,
        Type29,
        Type30,
        Type31
    }
}