namespace GFDLibrary
{
    public enum ResourceType
    {
        Invalid,
        ModelPack,
        ShaderCachePS3,
        ShaderCachePSP2 = 4,
        ShaderCachePS4 = 6,
        ModelPack_Metaphor = 8, // LITTLE_ENDIAN

        // These are all used as intermediary output formats
        TextureMap = 'R' << 24 | 'I' << 16 | 'G' << 8,
        TextureDictionary,
        Texture,
        ShaderPS3,
        ShaderPSP2,
        ShaderPS4,
        Model,
        Node,
        UserPropertyDictionary,
        Morph,
        MorphTarget,
        MorphTargetList,
        MaterialDictionary,
        ChunkType000100F9,
        ChunkType000100F8,
        AnimationPack,
        MaterialAttribute,
        Material,
        Light,
        Mesh,
        Camera,
        Epl,
        EplLeaf,
        Animation,
        AnimationBit29Data,
        AnimationLayer,
        AnimationController,

        EplAnimation,
        EplAnimationController,
        EplLeafDataHeader,
        EplEmbeddedFile,
        EplParticleEmitter,
        EplLeafCommonData,
        EplLeafCommonData2,
        EplDummy,
        EplParticle,
        EplFlashPolygon,
        EplFlashPolygonRadiation,
        EplFlashPolygonExplosion,
        EplFlashPolygonRing,
        EplFlashPolygonSplash,
        EplFlashPolygonCylinder,
        EplCirclePolygon,
        EplCirclePolygonRing,
        EplCirclePolygonTrajectory,
        EplCirclePolygonFill,
        EplCirclePolygonHoop,
        EplLightningPolygon,
        EplLightningPolygonRod,
        EplLightningPolygonBall,
        EplTrajectoryPolygon,
        EplWindPolygon,
        EplWindPolygonSpiral,
        EplWindPolygonExplosion,
        EplWindPolygonBall,
        EplModel,
        EplModel3DData,
        EplModel2DData,
        EplBoardPolygon,
        EplSquareBoardPolygon,
        EplRectangleBoardPolygon,
        EplObjectParticles,
        EplGlitterPolygon,
        EplGlitterPolygonExplosion,
        EplGlitterPolygonSplash,
        EplGlitterPolygonCylinder,
        EplGlitterPolygonWall,
        EplSmokeEffectParams,
        EplExplosionEffectParams,
        EplSpiralEffectParams,
        EplBallEffectParams,
        EplCircleEffectParams,
        EplStraightLineEffectParams,
        EplCamera,
        EplCameraMeshParams,
        EplCameraQuakeParams,
        EplLight,
        EplLightMeshData,
        EplLightSceneData,
        EplLightPointData,
        EplLightSpotData,
        EplPostEffect,
        EplPostEffectRadiationBlurData,
        EplPostEffectStraightBlurData,
        EplPostEffectNoiseBlurData,
        EplPostEffectDistortionBlurData,
        EplPostEffectFillData,
        EplPostEffectLensFlareData,
        EplPostEffectColorCorrectionData,
        EplPostEffectMonotoneData,
        EplPostEffectChromaticAberrationData,
        EplPostEffectColorCorrectionExcludeToonData,
        EplHelper,
        EplDirectionalParticles,

        MaterialParameterSetType0,
        MaterialParameterSetType1,
        MaterialParameterSetType2_3_13,
        MaterialParameterSetType4,
        MaterialParameterSetType5,
        MaterialParameterSetType6,
        MaterialParameterSetType7,
        MaterialParameterSetType8,
        MaterialParameterSetType9,
        MaterialParameterSetType10,
        MaterialParameterSetType11,
        MaterialParameterSetType12,
        MaterialParameterSetType14,
        MaterialParameterSetType15,
        MaterialParameterSetType16,
        MaterialParameterSetLegacy,

        ShaderMetaphorDX11,
        EplPostEffectLensFlareMakeData,
        EplPostEffectMotionBlurData,
        EplPostEffectAfterimageBlurData,

        ModelPack_Metaphor_BIG_ENDIAN = 0x8000000
    }
}